// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZeHUgSc3oOBed3we89ocM8aiu4vkVls4',
    appId: '1:229036647187:web:bdc93e3aa44e9bd497b0e6',
    messagingSenderId: '229036647187',
    projectId: 'flutter-lab-firebase-97067',
    authDomain: 'flutter-lab-firebase-97067.firebaseapp.com',
    storageBucket: 'flutter-lab-firebase-97067.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkqarG7A24rSH9gyOyYPKtHIZFE7GqRTs',
    appId: '1:229036647187:android:35fa99a6650a8f5c97b0e6',
    messagingSenderId: '229036647187',
    projectId: 'flutter-lab-firebase-97067',
    storageBucket: 'flutter-lab-firebase-97067.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChtNRPpEzYDbWZjLAMiDDbxYZdPnH0CiU',
    appId: '1:229036647187:ios:b0a9c7fcc238e9b697b0e6',
    messagingSenderId: '229036647187',
    projectId: 'flutter-lab-firebase-97067',
    storageBucket: 'flutter-lab-firebase-97067.appspot.com',
    iosClientId: '229036647187-cdqtns1ec75als0p78n54tdh273c9dbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChtNRPpEzYDbWZjLAMiDDbxYZdPnH0CiU',
    appId: '1:229036647187:ios:b0a9c7fcc238e9b697b0e6',
    messagingSenderId: '229036647187',
    projectId: 'flutter-lab-firebase-97067',
    storageBucket: 'flutter-lab-firebase-97067.appspot.com',
    iosClientId: '229036647187-cdqtns1ec75als0p78n54tdh273c9dbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
